#ifndef AVERMEDIA_OBS_MENU_MANAGER_GLOBAL_H
#define AVERMEDIA_OBS_MENU_MANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AVERMEDIA_OBS_MENU_LIBRARY)
#  define AVERMEDIA_OBS_MENU_EXPORT Q_DECL_EXPORT
#else
#  define AVERMEDIA_OBS_MENU_EXPORT Q_DECL_IMPORT
#endif // AVERMEDIA_OBS_MENU_LIBRARY

#endif // AVERMEDIA_OBS_MENU_MANAGER_GLOBAL_H
